Maven & выход в MenuBar & разбил generate
adfips/Robots pull request #3
Opened 2024-02-26 16:19 UTC by adfips

Извините произошла небольшая заминка, вроде исправил

2024-02-28 18:17 UTC, vpyzhyanov requested changes
Решение задачи хорошее. Вот только надо понять главное, пока вы не начнёте исправлять замечания и отвечать на вопросы, сдать задачу у вас не получится

2024-02-28 18:17 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        listenerClose();
Методы обычно что-то делают, поэтому лучше использовать в названии хотя бы один глагол. Здесь одни существительные. Например `initWindowCloseListener()`

2024-02-28 18:17 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
>   * Следует разделить его на серию более простых методов (или вообще выделить отдельный класс).
Разве вы это не сделали?

2024-02-28 18:17 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +     * Метод обрабатывающий выход из программы
На самом деле этот метод ничего не обрабатывает. Он просто меняет поведение при закрытии окна и устанавливает слушатель события

2024-02-28 18:17 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    private void exitHandler() {
имя метода и описания вообще никак не пересекаются. Название говорит "обработчик выхода", что бы это ни значило. То есть тут опять никакого глагола - действия.

Лучше писать что метод делает на самом деле, детали его работы описать можно, но только в качестве дополнительной информации, например `handleWindowClosingEvent`

2024-02-28 18:17 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        int option = javax.swing.JOptionPane.showOptionDialog(
замечание по прежнему не исправлено

2024-02-28 18:17 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        if (option == javax.swing.JOptionPane.YES_OPTION)
импорт

2024-02-28 18:17 UTC, vpyzhyanov commented on src/main/java/gui/MenuBar.java
> +public class MenuBar extends JMenuBar {
забыли JavaDoc

2024-02-28 18:17 UTC, vpyzhyanov commented on src/main/java/gui/MenuBar.java
> +    MainApplicationFrame frame;
опять нарушение ООП. Какое?

2024-02-28 18:17 UTC, vpyzhyanov commented on src/main/java/gui/MenuBar.java
> +        exitMenu.setMnemonic(KeyEvent.VK_E);
> Интересно, вы понимаете, что это значит?

Нет ответа на вопрос

2024-02-28 18:17 UTC, vpyzhyanov commented on src/main/java/gui/MenuBar.java
> +        JMenuItem exitMenuItem = new JMenuItem("Выход", KeyEvent.VK_S);
тут тоже поясните почему `VK_S`

2024-02-28 19:22 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    public void setLookAndFeel(String className) {
Этот метод должен быть private. Вы тут нарушили ООП этим публичным доступом. Подумайте что именно вы нарушили и придумайте как сделать его private

2024-03-01 10:17 UTC, adfips commented on src/main/java/gui/MainApplicationFrame.java
>   * Следует разделить его на серию более простых методов (или вообще выделить отдельный класс).
Задание? Сделал

2024-03-01 10:18 UTC, adfips commented on src/main/java/gui/MenuBar.java
> +    MainApplicationFrame frame;
Нарушение принципа инкапсуляции, поле frame не private

2024-03-01 10:18 UTC, adfips commented on src/main/java/gui/MenuBar.java
> +        exitMenu.setMnemonic(KeyEvent.VK_E);
JMenu("Выход") - создает поле в системном меню с названием выход
 exitMenu.setMnemonic(KeyEvent.VK_E); - устанавливает горячюю клавишу alt+e для открытие поля "Выход"

2024-03-01 10:18 UTC, adfips commented on src/main/java/gui/MenuBar.java
> +        JMenuItem exitMenuItem = new JMenuItem("Выход", KeyEvent.VK_S);
У всех других полей системного меню была эта клавиша, а какую лучше стоит поставить?

2024-03-01 10:18 UTC, adfips commented on src/main/java/gui/MainApplicationFrame.java
> +    public void setLookAndFeel(String className) {
я нарушил принцип инкапсуляции. Придумал такие варианты:
1)Можно сделать родительский класс
2)Можно сделать конкретные методы под конкретный фон
3)Можно создать отдельный пакет который будет отвечать за отображение окон и сделать доступ protected
Не знаю как лучше это исправить, выбрал 3

2024-03-18 16:49 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
>   * Следует разделить его на серию более простых методов (или вообще выделить отдельный класс).
Тогда не следует оставлять неактуальные комментарии

2024-03-18 16:52 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    private void exitHandler() {
> Лучше писать что метод делает на самом деле, детали его работы описать можно, но только в качестве дополнительной информации

К JavaDoc это замечание относится ровно так же, как и к названию. Похоже, что вы даже не читали моё замечание, а просто взяли то имя, что я предложил. Ок, больше не буду предлагать вариант, думайте сами.

2024-03-18 16:53 UTC, vpyzhyanov commented on src/main/java/gui/MenuBar.java
> +    MainApplicationFrame frame;
правильно

2024-03-18 16:56 UTC, vpyzhyanov commented on src/main/java/gui/MenuBar.java
> +        JMenuItem exitMenuItem = new JMenuItem("Выход", KeyEvent.VK_S);
Всё-таки вы не до конца понимаете, что такое Mnemonic. В данном случае слово "Выход" не содержит символа S. Впрочем тут используется русский язык, и английский букв там точно нет, но совершенно невозможно догадаться, что нужно нажать "S", чтобы выйти из программы. В чём логика?

2024-03-18 16:59 UTC, vpyzhyanov commented on src/main/java/gui/MenuBar.java
> +        JMenuItem exitMenuItem = new JMenuItem("Выход", KeyEvent.VK_S);
Наиболее правильным будет использованием код русской буквы, которая содержится в слове "Выход" и не пересекается с другими кнопками. Тогда она будет подчёркиваться.

![image](https://github.com/adfips/Robots/assets/71599019/7f1b9d1d-06e6-499c-8ea4-7407ebe1a53e)

2024-03-18 17:06 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    public void setLookAndFeel(String className) {
1. Очень плохой вариант. Тоже нарушение ООП, т.к. создаётся лишняя искусственная абстракция.
2. **Наилучший вариант**. Максимум контроля за состоянием класса, никто не сможет сделать неправомерные действия.
3. Вариант имеет право на существование, но я бы не назвал его лучшим, т.к. доступ внутри пакета всё равно неконтролируемый. А ещё вы сделали его неправильно. Модификатор доступа должен быть package-private, а не protected.

2024-03-18 17:07 UTC, vpyzhyanov commented
Как исправите оставшиеся замечания, можете мёрджить.

2024-03-18 17:07 UTC, vpyzhyanov commented
И не забудьте на паре вашу задачу показать

2024-03-18 18:10 UTC, merged