Реализовал сохранения состояний окон.
adfips/Robots pull request #4
Opened 2024-03-18 18:59 UTC by adfips

2024-03-31 16:07 UTC, vpyzhyanov requested changes
Есть замечания

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/gui/GameWindow.java
> +                throw new RuntimeException(e);
нужно писать человекочитаемое сообщение об ошибке, примерно так:

```
            } catch (PropertyVetoException e) {
                throw new RuntimeException("человекочитаемое сообщение об ошибке", e);
            }
```

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/gui/LogWindow.java
> +                String.format("%d,%d,%d,%d", getBounds().x, getBounds().y, getBounds().width, getBounds().height)
дублирование кода. Разве вас не смущает то, что в каждом классе вызывается **абсолютно одинаковый** код?

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/gui/LogWindow.java
> +                setIcon(Boolean.parseBoolean(icon));
дублирование

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/gui/LogWindow.java
> +    private Rectangle parseRectangle(String str) {
дублирование

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    protected GameWindow createGameWindow() {
зачем protected? Явно нарушена инкапсуляция

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    protected void setLookAndFeel(String className) {
зачем поменяли на protected? Даже не пользуетесь этим. Явно нарушена инкапсуляция

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        List<Component> allComponents = new ArrayList<>(List.of(desktopPane.getAllFrames()));
Создаёте новую коллекцию, а потом ещё одну коллекцию. Это очень неэффективно и по скорости и по памяти. Вот как должно быть:

![image](https://github.com/adfips/Robots/assets/71599019/0ac1abfb-5dab-49ee-8d19-69b734a99cb7)

И возвращается неизменяемая коллекция. Лучше всегда стараться возвращать неизменяемые объекты, так безопаснее.

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +                String.format("%d,%d,%d,%d", getBounds().x, getBounds().y, getBounds().width, getBounds().height)
дублирование

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    private Rectangle parseRectangle(String str) {
ну вы поняли)

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        String name = getClass().getName();
с одной стороны удобное решение, но у него есть существенный недостаток. Как только вы (или не вы) переименуете класс, то потеряете сохранённое состояние. Это плохо. Лучше создать константу с понятным именем и назначением, так вы хотя бы задумаетесь, если вдруг заходите её изменить.

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/saving/WindowSettings.java
> +            System.out.println(e.getMessage());
всегда старайтесь писать человекичитаемые ошибки

А для вывода ошибок есть специальный поток `System.err`

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/saving/WindowSettings.java
> +            if (configFile.createNewFile())
Создавать файл во время **загрузки**??? Может вы напутали что-то?

Если просто хотите проверить существует ли файл, то есть метод `exists()`

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/saving/WindowSettings.java
> +            throw new RuntimeException(e);
аналогично

2024-03-31 16:07 UTC, vpyzhyanov commented on src/main/java/saving/WindowSettings.java
> +            e.printStackTrace();
аналогично

2024-03-31 20:16 UTC, adfips commented on src/main/java/saving/WindowSettings.java
> +            if (configFile.createNewFile())
Я не всегда создаю файл. Проверяю есть ли файл с таким именем, если да, то возвращается false, иначе true 
В java doc так написано
![изображение_2024-04-01_004002891](https://github.com/adfips/Robots/assets/68304322/03a3d355-0c63-4b86-8238-48c4e7b47658)

2024-03-31 20:16 UTC, adfips commented on src/main/java/gui/MainApplicationFrame.java
> +        List<Component> allComponents = new ArrayList<>(List.of(desktopPane.getAllFrames()));
Да, так и правда лучше. Учту, спасибо

2024-03-31 20:16 UTC, adfips commented on src/main/java/gui/MainApplicationFrame.java
> +    protected void setLookAndFeel(String className) {
Ой это случайно, правда

2024-03-31 20:17 UTC, adfips commented on src/main/java/gui/MainApplicationFrame.java
> +    protected GameWindow createGameWindow() {
Не знаю, метод createLogWindow был protected и я по аналогии с ним написал protected
У метода createLogWindow тогда тоже стоит поменять модификатор доступа?

2024-03-31 20:17 UTC, adfips commented on src/main/java/gui/LogWindow.java
> +                String.format("%d,%d,%d,%d", getBounds().x, getBounds().y, getBounds().width, getBounds().height)
Смущает, очень смущает, но, честно говоря, я не знаю как решить эту проблему. Первое что приходит в голову - это использовать абстрактный класс, но в каждом классе, который реализует интерфейс, свои методы получения параметров, которые нужно сохранить. Тогда выходит, что абстрактный класс, надо будет множественно наследовать. Что сделать и как я не понимаю, дайте совет(

2024-04-01 06:37 UTC, adfips commented on src/main/java/gui/LogWindow.java
> +                String.format("%d,%d,%d,%d", getBounds().x, getBounds().y, getBounds().width, getBounds().height)
Я убрал дублирование, но я не знаю насколько это хорошее решение

2024-04-02 13:02 UTC, adfips commented on src/main/java/gui/LogWindow.java
> +                String.format("%d,%d,%d,%d", getBounds().x, getBounds().y, getBounds().width, getBounds().height)
Реализовал все в одном классе, отвечающем за сохранение и загрузку

2024-04-14 18:45 UTC, vpyzhyanov requested changes
Очень хорошо. Как исправите, можете мёрджить

2024-04-14 18:45 UTC, vpyzhyanov commented on src/main/java/saving/Savable.java
> +    String getFrameId();
Интерфейс - это контракт, он просто обязан иметь JavaDoc

2024-04-14 18:52 UTC, merged