3 task
adfips/Robots pull request #5
Opened 2024-04-14 19:07 UTC by adfips

реализация модели MVS, корректировка работы робота

2024-04-15 20:05 UTC, vpyzhyanov requested changes
Скинули чужое решение, за это получаете 0 баллов за задачу.

2024-04-15 20:05 UTC, vpyzhyanov commented on src/main/java/controller/GameController.java
> + * Контроллер GameWindow. Обновляет модель по таймеру и ...
Ничего не напоминает?

![image](https://github.com/adfips/Robots/assets/71599019/cb2764eb-0936-4aa3-af24-b8b4afd1563c)

Класс один в один.

2024-04-15 20:06 UTC, vpyzhyanov commented
А ещё получаете на погоны 2 предупреждения. Если будет ещё одно то будете исключены из группы extra. Что-то я слишком добрый стал, по идее вас сразу надо исключать за такое.

2024-04-16 02:49 UTC, adfips commented on src/main/java/controller/GameController.java
> + * Контроллер GameWindow. Обновляет модель по таймеру и ...
Я не знал как решить задачу, изучил и взял у него решение только GameController и конструктор GameVisualizer, тем более решение Димы вы вроде как одобрили.  Я скинул чужой контроллер, но не чужое решение всей задачи.
Оценивается же вроде как знание студента, тем более даже в регламенте и на парах ничего не было сказано про использование чужого кода, в конце концов мы же библиотеками пользуемся:) Хотя с другой стороны я в extra. В любом случае решение за вами.

2024-04-21 15:56 UTC, vpyzhyanov commented
![image](https://github.com/adfips/Robots/assets/71599019/6aa36540-837a-4d6f-ba56-eb60d4c9916d)

forse push в открытом пулл реквесте мягко говоря не приветствуется

2024-04-21 16:13 UTC, vpyzhyanov requested changes
есть замечания

2024-04-21 16:13 UTC, vpyzhyanov commented on src/main/java/controller/Controller.java
> +    Robot robot;
нарушена инкапсуляция. Поле используется только в этом классе

2024-04-21 16:13 UTC, vpyzhyanov commented on src/main/java/controller/Controller.java
> +    public Robot getRobot() {
зачем? Инкапсуляции не будет даже если сделаете поле private. Не надо контроллеру раздавать модель кому попало. Кому нужна модель у них она будет и без участия контроллера.

2024-04-21 16:13 UTC, vpyzhyanov commented on src/main/java/gui/CoordinateRobotWindow.java
> +        controller.getRobot().addListener(this);
вы разве не видите, что этому классу контроллер не нужен?! Ему нужна только модель. Вот модель и передавайте в конструктор. Не надо лишних посдердников

2024-04-21 16:13 UTC, vpyzhyanov commented on src/main/java/gui/GameVisualizer.java
> +        robot = controller.getRobot();
вы разве не видите, что этому классу контроллер не нужен?! Ему нужна только модель. Вот модель и передавайте в конструктор. Не надо лишних посдердников

А на самом деле этому классу контроллер очень нужен, и очень странно, что вы его не используете. Очевидно у вас представление меняет модель напрямую, а это уже не MVC

![image](https://github.com/adfips/Robots/assets/71599019/12c14930-863e-4660-9db3-058ce57d2ea6)

2024-04-21 16:13 UTC, vpyzhyanov commented on src/main/java/gui/GameVisualizer.java
> +        if (evt.getPropertyName().equals("propertyName")) {
что за `"propertyName"`? Либо назовите нормально (нормально - это когда текст соответствует действительности и **несёт смысл**), либо уберите

2024-04-21 16:13 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        controller.start();
если бы вы создали контроллер там где нужно, вам бы не пришлось его отдельно запускать. Да и зачем вообще запускать контроллер. На этом уровне абстракции это вообще не очевидно и непонятно.

2024-04-21 16:13 UTC, vpyzhyanov commented on src/main/java/model/Robot.java
> +    public double getM_robotPositionX() {
в Java не принято использовать символ `_` в именах классов, методов и полей. Только для констант.

2024-04-22 20:02 UTC, vpyzhyanov approved these changes
Хорошо, можете мёрджить

2024-04-23 03:12 UTC, merged