реализовал структуру данных для хранения записей
adfips/Robots pull request #6
Opened 2024-04-29 15:46 UTC by adfips

2024-04-30 15:39 UTC, vpyzhyanov requested changes
Есть замечание.

Так и не удалось показать на паре правильное поведение.

2024-04-30 15:39 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
>  public class LogWindowSource
обратите внимание на этот JavaDoc (не надо делать вид, что вы его не заметили😉)

2024-04-30 18:23 UTC, vpyzhyanov requested changes
есть замечания

2024-04-30 18:23 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
> +                    activeListeners = listeners.toArray(new LogChangeListener[0]);
этим вы полностью обесценили свои старания по исправлению утечки памяти и ничего по сути не исправили. Слабые ссылки нужно использовать во всех слушателях.

2024-04-30 18:23 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
> +            m_listeners.remove(new WeakReference<>(listener));
Это работать не будет. Как думаете почему?

2024-04-30 18:39 UTC, adfips commented on src/main/java/log/LogWindowSource.java
> +            m_listeners.remove(new WeakReference<>(listener));
remove под капотом использует equals а у слабых ссылок не определен этот метод, а по умолчанию сравниваются ссылки на объекты.

2024-04-30 19:27 UTC, vpyzhyanov requested changes
Проблема не исправлена. Притом добавлена другая. Не годится такое решение

2024-04-30 19:27 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
> +            m_listeners.remove(new WeakReference<>(listener));
правильно

2024-04-30 19:27 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
> +            m_listeners.remove(new WeakReference<>(listener));
Вот только неправильно то, что вы до сих пот не изменили эту строчку. Она больше не нужна и должна быть удалена

2024-04-30 19:27 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
> -    private volatile LogChangeListener[] m_activeListeners;
это неправильно. Ваша программа начала жутко тормозить. Как думаете почему?

2024-04-30 19:27 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
> +                    activeListeners = listeners.toArray(new LogChangeListener[0]);
Не исправлено

2024-04-30 20:13 UTC, adfips commented on src/main/java/log/LogWindowSource.java
> -    private volatile LogChangeListener[] m_activeListeners;
активные слушатели нужны, что каждый раз не синхронизировалось при добавлении лога?
Таким образом у нас потоки не будут блокироваться лишний раз и мы оптимизируем работу

2024-05-05 09:59 UTC, vpyzhyanov approved these changes
Хорошо, как исправите последний замечания, можете мёрджить.

2024-05-05 09:59 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
> -    private volatile LogChangeListener[] m_activeListeners;
правильно

2024-05-05 09:59 UTC, vpyzhyanov commented on src/main/java/log/LogWindowSource.java
> +    private volatile ArrayList<WeakReference<LogChangeListener>> m_activeListeners;
Я учил вас использовать интерфейсы, а не классы

2024-05-05 10:44 UTC, merged